include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
  exclude:
    - "lib/gen/**/*.dart"
    - "**/*.chopper.dart"

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    avoid_function_literals_in_foreach_calls: false
    avoid_positional_boolean_parameters: false
    unnecessary_raw_strings: false
    annotate_overrides: false
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
